### ISSUE TITLE
Unnecessary encapsulation

### ISSUE THREAD

**Issue by ghost** [brendanberg/interfascia#1]
Abstract class GUIComponent is package private and should be public. I can't keep a general list of GUIComponents because of this.

GUIController should have a method to be reset (remove all components at once) and/or to get a list of all components (see previous note).

The lack of these methods make it hard to use Interfascia with applications that change user context. The reference to the controller is kept by the Processing Core and the user can't unsubscribe the controller, just make it invisible and add a new GUIController each time the context changes. This leaves the Core with a whole bunch of invisible GUIControllers.

Interfascia is great for applications that don't change context. But some things that make it a bit easier to use for these programs make it impossible to use Interfascia in programs that do change context.

**Comment by brendanberg** [comment]
It's been a while since I've been actively working on the project, but the move to github is part of an effort to revive it. So thanks for being the first to open a github ticket!

It seems like the functionality you're requesting would be better served by being able to unregister a `GUIController` from its parent `PApplet`. Instead of removing all the components from the controller, each context would have its own controller. The `GUIController` could then be unregistered from the `PApplet` on context changes.

The `GUIController` contains information about the component with keyboard focus, the components' look and feel, etc., so it's more than just a list of `GUIComponent` instances. I think it makes sense to preserve this information even if a given controller is not currently registered with the applet.

Would this alternative work for your use case? Is it still important to make `GUIComponent` public? (It may be nice at some point to allow developers to create custom subclasses...)

**Comment by ghost** [comment]
Keep up the good work! It might too late for me to use Interfascia in the way I intended, I'm learning a big deal from it and I think I'll be playing around with it for a while.

I think unregistering is a workable solution. And it doesn't break working code, so that's nice.

I still have some doubts about the `actionPerformed()` system when used with changing contexts, but I don't have the opportunity to play with that right now, too much school stuff and such. 

I still think `GUIComponent` should be public. As you said, I might want to extend the class, and there are `GUIController` methods that return a `GUIComponent`. Making it public also doesn't hurt the encapsulation of the system.

**Comment by brendanberg** [comment]
Fixed in #14
